import { deserialize, serialize } from '@engine/core/knockout'
import type { StorageAdapter } from '@engine/core/knockout'
import type { KnockoutState } from '@engine/core/types'

/**
 * Browser localStorage implementation of the core StorageAdapter interface.
 * Browser APIs stay out of src/core -- this is the frontend-side adapter.
 * `key` is always the string produced by core's `storageKey()`.
 */
const NS = 'gallagioloot'
const KNOCKOUT_PREFIX = `${NS}:knockout:`
const SETTINGS_PREFIX = `${NS}:settings:`
const LAST_URL_PREFIX = `${NS}:lastUrl:`
const LAST_TOPGEAR_URL_PREFIX = `${NS}:lastTopGearUrl:`
const VOIDCORE_PREFIX = `${NS}:voidcore:`

export class LocalStorageAdapter implements StorageAdapter {
  async load(key: string): Promise<KnockoutState | null> {
    const raw = localStorage.getItem(KNOCKOUT_PREFIX + key)
    if (!raw) return null
    try {
      return deserialize(raw)
    } catch {
      return null
    }
  }

  async save(key: string, state: KnockoutState): Promise<void> {
    localStorage.setItem(KNOCKOUT_PREFIX + key, serialize(state))
  }

  async list(): Promise<string[]> {
    const keys: string[] = []
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i)
      if (k && k.startsWith(KNOCKOUT_PREFIX)) keys.push(k.slice(KNOCKOUT_PREFIX.length))
    }
    return keys.sort()
  }

  async remove(key: string): Promise<void> {
    localStorage.removeItem(KNOCKOUT_PREFIX + key)
  }
}

/**
 * One-time migration for knockout state saved under a legacy key with an empty region
 * and/or realm segment (e.g. "::icemagus:raid-vault-mythic"), from before the Raidbots
 * normalizer resolved region/realm from the simc profile. If exactly one legacy key shares
 * the resolved key's character and difficulty, its stored state is copied to `resolvedKey`
 * (region/realm filled in) and the legacy key removed. If more than one legacy key matches
 * (ambiguous), none are migrated and they're logged. No-op when `resolvedKey` already has
 * data, is itself legacy-shaped (empty region/realm), or nothing matches. Returns the
 * migrated state when a migration happened, else null.
 *
 * Signature drafted for and body first generated by qwen2.5-coder:7b (Ollama), then edited
 * for a null-safe localStorage.key() guard and to scope the "empty segment" check to
 * region/realm only.
 */
export function migrateLegacyLocationKey(resolvedKey: string): KnockoutState | null {
  const segments = resolvedKey.split(':')
  if (segments.length !== 4) return null
  const [region, realm, character, difficulty] = segments
  if (region === '' || realm === '') return null

  if (localStorage.getItem(KNOCKOUT_PREFIX + resolvedKey) !== null) return null

  const candidateKeys: string[] = []
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i)
    if (!key || !key.startsWith(KNOCKOUT_PREFIX)) continue
    const legacyKey = key.slice(KNOCKOUT_PREFIX.length)
    if (legacyKey === resolvedKey) continue
    const parts = legacyKey.split(':')
    if (parts.length !== 4) continue
    const isLegacy = parts[0] === '' || parts[1] === ''
    if (isLegacy && parts[2] === character && parts[3] === difficulty) candidateKeys.push(legacyKey)
  }

  if (candidateKeys.length === 1) {
    try {
      const raw = localStorage.getItem(KNOCKOUT_PREFIX + candidateKeys[0])
      if (raw === null) return null
      const state = { ...deserialize(raw), region, realm }
      localStorage.setItem(KNOCKOUT_PREFIX + resolvedKey, serialize(state))
      localStorage.removeItem(KNOCKOUT_PREFIX + candidateKeys[0])
      return state
    } catch {
      return null
    }
  }
  if (candidateKeys.length > 1) {
    console.warn(
      `[gallagioloot] Not migrating legacy knockout keys for "${character}" (${difficulty}): ${candidateKeys.length} ambiguous matches`,
      candidateKeys
    )
  }
  return null
}

export type StoredSettings = {
  thresholdPct: number
  /** Voidcores to spend this week when lowered below Voidcores on hand; null = spend everything on hand (the default). */
  spendOverride: number | null
  /** Voidcores earned per week when set by hand; null = the default from the season week (1, or 2 from week 8). */
  earnedPerWeek: number | null
  seasonWeek: number | null
  /** Weeks left in the season after this one. */
  weeksLeft: number | null
}

export const DEFAULT_STORED_SETTINGS: StoredSettings = {
  thresholdPct: 0.2,
  spendOverride: null,
  earnedPerWeek: null,
  seasonWeek: null,
  weeksLeft: null,
}

function readJSON<T>(key: string): T | null {
  const raw = localStorage.getItem(key)
  if (!raw) return null
  try {
    return JSON.parse(raw) as T
  } catch {
    return null
  }
}

const countOrNull = (v: unknown): number | null => (typeof v === 'number' && Number.isFinite(v) && v >= 0 ? Math.floor(v) : null)

/**
 * Stored settings, with v2.08's `rollsAvailable` (a weekly spend cap that doesn't exist -- operator
 * ruling 2026-09-25) migrated away: 2 meant "season week 8 or later", which is now the earning
 * rule, so it becomes 2 Voidcores earned per week unless one is already stored; 1 was the default
 * and is dropped. The migrated shape is written back on the next save.
 */
export function loadSettings(key: string): StoredSettings {
  const raw = readJSON<Record<string, unknown>>(SETTINGS_PREFIX + key)
  if (!raw || typeof raw !== 'object') return DEFAULT_STORED_SETTINGS
  const earned = countOrNull(raw.earnedPerWeek) ?? (raw.rollsAvailable === 2 ? 2 : null)
  return {
    thresholdPct: typeof raw.thresholdPct === 'number' && Number.isFinite(raw.thresholdPct) ? raw.thresholdPct : DEFAULT_STORED_SETTINGS.thresholdPct,
    spendOverride: countOrNull(raw.spendOverride),
    earnedPerWeek: earned,
    seasonWeek: countOrNull(raw.seasonWeek),
    weeksLeft: countOrNull(raw.weeksLeft),
  }
}

export function saveSettings(key: string, settings: StoredSettings): void {
  localStorage.setItem(SETTINGS_PREFIX + key, JSON.stringify(settings))
}

export function loadLastReportUrl(key: string): string | null {
  return localStorage.getItem(LAST_URL_PREFIX + key)
}

export function saveLastReportUrl(key: string, url: string): void {
  localStorage.setItem(LAST_URL_PREFIX + key, url)
}

export function loadLastTopGearUrl(key: string): string | null {
  return localStorage.getItem(LAST_TOPGEAR_URL_PREFIX + key)
}

export function saveLastTopGearUrl(key: string, url: string): void {
  localStorage.setItem(LAST_TOPGEAR_URL_PREFIX + key, url)
}

export function loadVoidcoreCount(key: string): number {
  const raw = localStorage.getItem(VOIDCORE_PREFIX + key)
  const n = raw ? Number(raw) : 0
  return Number.isFinite(n) && n >= 0 ? n : 0
}

export function saveVoidcoreCount(key: string, count: number): void {
  localStorage.setItem(VOIDCORE_PREFIX + key, String(Math.max(0, Math.floor(count))))
}

const REPORT_SET_PREFIX = `${NS}:reportSet:`

/**
 * The set of report URLs loaded together for one character (raid difficulties + one
 * Mythic+ report), keyed by `characterKey()` (`region:realm:character`, no difficulty).
 * Null when nothing was saved -- callers fall back to the per-key last URL.
 */
export function loadReportSet(characterKey: string): string[] | null {
  const urls = readJSON<unknown>(REPORT_SET_PREFIX + characterKey)
  return Array.isArray(urls) ? urls.filter((u): u is string => typeof u === 'string' && u.length > 0) : null
}

export function saveReportSet(characterKey: string, urls: string[]): void {
  localStorage.setItem(REPORT_SET_PREFIX + characterKey, JSON.stringify(urls))
}
