import type { LootTableEncounter, NormalizedReport } from '../types'
import type { KnockoutState } from './types'

/**
 * A curio (Ula'tek's Slumbering Coil Curio) cannot be won with a bonus roll -- Erick's
 * Adventure Journal ruling 2026-09-24 -- so it is never a pool entry. Older builds did
 * model it as one merged pool entry and could have saved a knockout entry against one of
 * its tier pieces, recorded under the curio boss's encounter id.
 *
 * `${encounterId}:${itemId}` for every curio-routed row of this report and loot table
 * (`viaCurio`), i.e. the identity of a stored knockout entry that referred to the curio.
 */
export function curioEntryKeys(report: Pick<NormalizedReport, 'items'>, lootTable?: LootTableEncounter[]): Set<string> {
  const keys = new Set<string>()
  for (const item of report.items) {
    if (item.viaCurio) keys.add(`${item.encounterId}:${item.itemId}`)
  }
  for (const encounter of lootTable ?? []) {
    for (const row of encounter.items) {
      if (row.viaCurio) keys.add(`${encounter.encounterId}:${row.itemId}`)
    }
  }
  return keys
}

/**
 * Drops stored knockout entries that refer to a curio (see `curioEntryKeys`). Returns the
 * same `state` object when nothing was dropped. Signature and body first generated by
 * qwen2.5-coder:7b (Ollama), then reformatted to the repo's style.
 */
export function dropCurioEntries(state: KnockoutState, curioKeys: ReadonlySet<string>): KnockoutState {
  const entries = state.entries.filter((entry) => !curioKeys.has(`${entry.encounterId}:${entry.itemId}`))
  return entries.length === state.entries.length ? state : { ...state, entries }
}
